# --- export PATH -----------------------------------------------------------------
export PATH="/usr/local/opt/node@14/bin:$PATH"
export PATH="$PATH:$HOME/.ft"
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH:$HOME/go/bin"

# --- import script -----------------------------------------------------------------
source /Users/leewish/work/bin/z.sh


# --- alias -----------------------------------------------------------------
alias help=tldr
