# --- export PATH -----------------------------------------------------------------
export PATH="/usr/local/opt/node@14/bin:$PATH"
export PATH="$PATH:$HOME/.ft"
export PATH="/usr/local/opt/sphinx-doc/bin:$PATH:$HOME/go/bin"
export PATH="$PATH:/snap/bin"

 export FZF_DEFAULT_COMMAND='fd -E .git -E .ccls-cache -E build'
# --- import script -----------------------------------------------------------------


# --- alias -----------------------------------------------------------------
alias help=tldr
